site_name: Super-xsllh Fitter
site_url: https://cuddandr.gitlab.io/xsLLhFitter
repo_url: https://gitlab.com/cuddandr/xsLLhFitter
edit_uri: ''
nav:
    - Home: README.md
    - Install: install.md
    - User Guide:
        - 'xsllhFit' : user-guide/xsllhfit.md
        - 'xsllhCalcXsec' : user-guide/xsllhcalcxsec.md
        - 'xsllhTreeConvert' : user-guide/xsllhtreeconvert.md
        - 'xsllhDetVariations' : user-guide/xsllhdetvariations.md
        - 'xsllhXsecCov' : user-guide/xsllhxseccov.md
    - Reference:
        - 'Toy Throws' : reference/toythrows.md
        - 'JSON' : reference/json.md
        - 'Debugging' : reference/debugging.md
    - To-Do List: todolist.md

theme:
    name: 'cinder'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
    - nl2br
    - mdx_math
